name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latesst
    stops:
      -uses: action/check@2
      -name: Run a one-line script
      run: echo Hello, world!

      -name: Run a mutil-line script
      run: 
          echo Add other actions to build,
          echo test, and deploy your project